[project]
name = "demo-routing"
authors = [
    { name="Reece Holmdahl", email="reece@pywire.dev" },
]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pywire",
]

# This is not a distributable package, just for dependency management

