[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pywire-examples"
dynamic = ["version"]
description = "Examples for pywire"
requires-python = ">=3.12"
dependencies = []


# Workspace members are now managed by the root pyproject.toml

