name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: "Check Examples"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout pywire
        uses: actions/checkout@v4
        with:
          repository: pywire/pywire
          path: pywire
          token: ${{ secrets.GH_PAT }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
      
      - name: Install dependencies
        run: uv sync

      - name: Run Checks
        run: ./scripts/check
